{
 "title": "Состояние сервисов",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "60s",
 "panels": [
  {
   "title": "tracker.leads.su",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://tracker.leads.su\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "api.leads.su",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://api.leads.su\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "leads.su",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://leads.su\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}